### ISSUE TITLE
OONI Run v2: New OONI Run Links do not work non-Google devices

### ISSUE THREAD

**Issue by jbonisteel** [TheTorProject/ooni-run#153]
Steps to reproduce:

(using BrowserStack)

- Load OONI Run v2 app in G9 device
- Open up Chrome 
- Paste in new OONI Run v2 link

Expected results: user should see a prompt telling them to continue in app
Actual results: nothing happens - the user is not prompted to open in the app. You just stay on the google homepage

![screenshot-Motorola Moto G9 Play-10 0](https://github.com/ooni/run/assets/15895520/40f578d0-b850-4b8b-ac43-9e4125391870)

**Comment by jbonisteel** [comment]
I have been testing this on additional devices using BrowserStack

- Samsung Galaxy s20 - doesnt work, nothing happens when you try and load the url
- Samsung S8 - seems to try and load play store, despite app being installed
- Motorola G71 5G - also does not work. Older/current style of OONI run links also does not work on Firefox (works on Chrome)

**Comment by hellais** [comment]
Mobile deep links need to be tapped on in order to trigger the action. You can tap on a mobile deep link by copying it into the notes app and then clicking on it. Alternatively you can receive the link via some messagging app and then tap on it (most common use case).

It's expected behavior that it would not trigger deep linking behaviour if you copy paste the link into a browser.

That said we should have a way to trigger the deep linking behaviour from the view link button (I recall we had this in the mockups). Does that not appear when you open the link?

**Comment by hellais** [comment]
The reason why you are seeing it working on some browsers, is probably because you are hitting our specific server-side redirection logic, however that is not meant to be reached unless there was a bug in handling deep linking behavior. 

In order to properly test mobile deep linking what you should do is:

1. Paste OONI Run link into the notes app or send it to you via a message
2. Click on the link from the app
3. Check if the deep linking behaviour is seen

**Comment by jbonisteel** [comment]
I am going to close this for now, because when testing on my physical device and following the steps outlined above - the links work
